#!/usr/bin/env bash
# Regenerate the frontend's canonical IANA timezone list from Linux tzdata.
set -euo pipefail

zoneinfo_dir=${TZDATA_DIR:-/usr/share/zoneinfo}
table="$zoneinfo_dir/zone.tab"
output=${1:-web/src/lib/timezones.ts}

if [[ ! -r "$table" ]]; then
  printf 'cannot read Linux timezone table: %s\n' "$table" >&2
  exit 1
fi

version=$(awk '$1 == "#" && $2 == "version" { print $3; exit }' "$zoneinfo_dir/tzdata.zi")
version=${version:-unknown}

mapfile -t timezones < <(awk -F '\t' '!/^#/ && NF { print $3 }' "$table" | LC_ALL=C sort -u)

{
  printf '// Code generated by scripts/update-timezones.sh from Linux tzdata %s zone.tab; DO NOT EDIT.\n' "$version"
  printf '// The table contains canonical IANA locations, not compatibility aliases.\n\n'
  printf 'export const TIMEZONES = [\n'
  printf "  'UTC',\n"
  for timezone in "${timezones[@]}"; do
    printf "  '%s',\n" "$timezone"
  done
  printf '] as const;\n\n'
  printf 'const timezoneSet = new Set<string>(TIMEZONES);\n\n'
  printf 'export function isSupportedTimezone(timezone: string): boolean {\n'
  printf '  return timezoneSet.has(timezone);\n'
  printf '}\n'
} >"$output"
